/*NORMAL DOMAINS*/
CREATE DOMAIN T_EMAIL AS TEXT NOT NULL;
CREATE DOMAIN T_HASH AS VARCHAR(100) NOT NULL;
/*CHARACTER DOMAINS*/
CREATE DOMAIN T_NAME AS VARCHAR(20) NOT NULL;
CREATE DOMAIN T_LEVEL AS BIGINT NOT NULL;
CREATE DOMAIN T_ATTACK AS BIGINT NOT NULL;
CREATE DOMAIN T_HP AS BIGINT NOT NULL;
CREATE DOMAIN T_EXP AS BIGINT NOT NULL;
CREATE DOMAIN T_ROLE_CLASS AS TEXT NOT NULL;



CREATE TABLE LOGIN (
    ID_LOGIN SERIAL PRIMARY KEY,
    EMAIL T_EMAIL UNIQUE,
    PASSWORD T_HASH
);


CREATE TABLE CLASS_TYPE (
    ID_CLASS_TYPE SERIAL PRIMARY KEY,
    NAME T_NAME,
    ATTACK T_ATTACK,
    HP T_HP
);

CREATE TABLE USER_CHARACTER (
    ID_USER SERIAL PRIMARY KEY,
    NAME T_NAME,
    EXPERIENCE T_EXP,
    LEVEL T_LEVEL,
    JOINED TIMESTAMP,
    ID_LOGIN T_ID,
    ID_CLASS_TYPE T_ID,
    FOREIGN KEY (ID_LOGIN) REFERENCES LOGIN (ID_LOGIN),
    FOREIGN KEY (ID_CLASS_TYPE) REFERENCES CLASS_TYPE (ID_CLASS_TYPE)
);


CREATE TABLE USER_CHARACTER (
    ID_USER SERIAL PRIMARY KEY,
    NAME T_NAME,
    ATTACK T_ATTACK,
    HP T_HP,
    EXPERIENCE T_EXP,
    LEVEL T_LEVEL,
    JOINED TIMESTAMP,
    ID_LOGIN SERIAL,
    ID_CLASS_TYPE SERIAL,
    FOREIGN KEY (ID_LOGIN) REFERENCES LOGIN (ID_LOGIN),
    FOREIGN KEY (ID_CLASS_TYPE) REFERENCES CLASS_TYPE (ID_CLASS_TYPE)
);


delete from login where 1=1;
delete from user_character where 1=1;
ALTER TABLE LOGIN ADD UNIQUE(email);